Repository Laravel-Backpack/theme-coreuiv2, pull requests merged in 2023-06, with the labels that each got.

#8 move all widgets to CRUD
  resources/views/widgets/alert.blade.php
  resources/views/widgets/card.blade.php
  resources/views/widgets/div.blade.php
  resources/views/widgets/inc/wrapper_end.blade.php
  resources/views/widgets/inc/wrapper_start.blade.php
  resources/views/widgets/jumbotron.blade.php
  resources/views/widgets/progress.blade.php
  resources/views/widgets/progress_white.blade.php
  resources/views/widgets/script.blade.php
  resources/views/widgets/style.blade.php
  resources/views/widgets/view.blade.php
  src/AddonServiceProvider.php
  src/AutomaticServiceProvider.php
Labels: Priority: MUST

#13 docs publish config
  readme.md
  src/AutomaticServiceProvider.php
Labels: Priority: MUST

#12 fix repeatable container
  resources/assets/css/coreuiv2.css
Labels: Priority: MUST

#14 add popper js
  resources/views/inc/theme_scripts.blade.php
Labels: Priority: MUST

#9 add view components for menus
  resources/views/components/menu-dropdown-item.blade.php
  resources/views/components/menu-dropdown.blade.php
  resources/views/components/menu-item.blade.php
  resources/views/components/menu-separator.blade.php
Labels: Priority: MUST

#15 use ThemeServiceProvider
  src/AddonServiceProvider.php
  src/AutomaticServiceProvider.php
Labels: Priority: MUST, Priority: SHOULD, Size: XS

#17 add dropdown menu header component
  resources/assets/css/coreuiv2.css
  resources/views/components/menu-dropdown-header.blade.php
Labels: Priority: MUST, Priority: SHOULD
